---
common_timezone: "America/New_York"
common_keyring_dir: "/etc/apt/keyrings"
common_nfs_dir: "/mnt/storage"
common_packages:
  - sudo
  - curl
  - git
  - vim
  - make
  - gnupg
  - nfs-common
  - lsb-release
  - software-properties-common
  - jq
  - unzip
  - ca-certificates
  - openssl
  - rsync
  - python3-pip
  - python3-jsondiff
  - python3-docker