networks:
  - name: bz-public-net
    scope: swarm
    driver: overlay
    internal: true
    interal: false
  - name: bz-docker-socket-proxy-net
    scope: swarm
    driver: overlay
    internal: true
  - name: bz-internal-net
    scope: swarm
    driver: overlay
    internal: true
