$ANSIBLE_VAULT;1.2;AES256;dev
64633935666139613538353435303238376232626636373235643465363138656463636362623264
6565383165336638363263633238363132643730346338640a313930636564366664626165393339
39356464343265643331353032663863333963396137643037326238346537616462306339316330
3531616635363636630a373139323931336234313762636563616130643539356231653537633438
3838
